# Generated by Django 3.1.12 on 2021-07-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='request',
            name='purpose',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
