# Generated by Django 3.1.12 on 2021-07-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_auto_20210720_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='last_name',
            new_name='school_id',
        ),
    ]
