# Generated by Django 3.1.12 on 2021-07-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0004_auto_20210720_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='purpose',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='request',
            name='school_id',
            field=models.CharField(max_length=15),
        ),
    ]
