# Generated by Django 3.1.13 on 2021-07-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0005_auto_20210720_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
